"use client";
import { zodResolver } from "@hookform/resolvers/zod";
import { FormProvider, useForm, FieldValues } from "react-hook-form";
import * as z from "zod";
import BasicSettings from "./BasicSettings";
import HorizontalLine from "./HorizontalLine";
import TestCall from "./TestCall";
import { agentFormData, agentSchema } from "@/lib/agentSchema";
import IntroductionSentence from "./IntroductionSentence";
import ReferenceData from "./ReferenceData";
import ProductDescription from "./ProductDescription";
import CallScript from "./CallScript";
import { Button } from "@/components/ui/button";

const AgentForm = () => {
  const form = useForm<z.infer<typeof agentSchema>>({
    resolver: zodResolver(agentSchema),
    defaultValues: {
      callType: "Outbound (Make Calls)",
      agentName: "",
      description: "",
      language: "",
      voice: "",
      prompt: "",
      model: "",
      latency: "0.6s",
      speed: "90%",
      firstName: "",
      lastName: "",
      gender: "",
      email: "",
      phoneNumber: "",
      testCustomerListVariables: "",
      variable1: "",
      sentences: [
        {
          content: "",
          isAutoGenerated: false,
        },
      ],
      delay: "",
      callScript: "",
    },
    mode: "onChange",
  });
  const onSubmit = (data: agentFormData) => {
    console.log("Form submitted:", data);
    // Handle form submission
  };

  const onError = (errors: FieldValues) => {
    console.error("Form errors:", errors);
  };
  return (
    <div>
      <FormProvider {...form}>
        <form onSubmit={form.handleSubmit(onSubmit, onError)}>
          {" "}
          <BasicSettings />
          <HorizontalLine />
          <ProductDescription />
          <HorizontalLine />
          <CallScript />
          <HorizontalLine />
          <IntroductionSentence />
          <HorizontalLine />
          <ReferenceData />
          <HorizontalLine />
          <TestCall />
          <div className="border-t-2 mt-4">
            <Button type="submit" className="mt-4 ml-auto block cursor-pointer">
              Save Agent
            </Button>
          </div>
        </form>
      </FormProvider>
    </div>
  );
};

export default AgentForm;
