import * as z from "zod";

export const basicSettingsSchema = z.object({
  callType: z
    .string()
    .min(1, "Call Type is required")
    .refine(
      (val) =>
        ["Inbound (Receive Calls)", "Outbound (Make Calls)"].includes(val),
      { message: "Please enter a valid call type" },
    ),

  agentName: z
    .string()
    .min(1, "Agent Name is required")
    .min(2, "Agent Name must be at least 2 characters")
    .max(50, "Agent Name cannot exceed 50 characters"),

  description: z
    .string()
    .max(500, "Description cannot exceed 500 characters")
    .optional(),

  language: z
    .string()
    .min(1, "Language is required")
    .refine(
      (val) =>
        ["english", "spanish", "french", "german", "arabic"].includes(
          val.toLowerCase(),
        ),
      { message: "Please select a valid language" },
    ),

  voice: z
    .string()
    .min(1, "Voice is required")
    .refine(
      (val) =>
        ["voice1", "voice2", "voice3", "voice4"].includes(val.toLowerCase()),
      { message: "Please select a valid voice" },
    ),

  prompt: z
    .string()
    .min(1, "Prompt is required")
    .refine(
      (val) =>
        [
          "prompt1",
          "prompt2",
          "sales",
          "support",
          "collections",
          "custom",
        ].includes(val.toLowerCase()),
      { message: "Please select a valid prompt" },
    ),

  model: z
    .string()
    .min(1, "Model is required")
    .refine(
      (val) =>
        ["model1", "model2", "gpt-3.5", "gpt-4", "claude-3", "gemini"].includes(
          val.toLowerCase(),
        ),
      { message: "Please select a valid model" },
    ),

  latency: z
    .string()
    .min(1, "Latency is required")
    .refine(
      (val) => {
        const numValue = parseFloat(val.replace("s", ""));
        return (
          numValue >= 0.3 && numValue <= 1 && Number.isInteger(numValue * 10)
        );
      },
      {
        message: "Latency must be between 0.3s and 1.0s in 0.1s increments",
      },
    ),

  speed: z
    .string()
    .min(1, "Speed is required")
    .refine(
      (val) => {
        const numValue = parseInt(val.replace("%", ""));
        return numValue >= 90 && numValue <= 130 && numValue % 5 === 0;
      },
      {
        message: "Speed must be between 90% and 130% in 5% increments",
      },
    ),
});

export const testCallSchema = z.object({
  firstName: z
    .string()
    .min(1, "First name is required")
    .min(2, "First name must be at least 2 characters")
    .max(50, "First name cannot exceed 50 characters")
    .regex(/^[a-zA-Z\s]*$/, "First name can only contain letters and spaces"),

  lastName: z
    .string()
    .min(1, "Last name is required")
    .min(2, "Last name must be at least 2 characters")
    .max(50, "Last name cannot exceed 50 characters")
    .regex(/^[a-zA-Z\s]*$/, "Last name can only contain letters and spaces"),

  gender: z
    .string()
    .min(1, "Gender is required")
    .refine((val) => ["male", "female"].includes(val.toLowerCase()), {
      message: "Please select a valid gender",
    }),

  email: z
    .string()
    .min(1, "Email is required")
    .email("Please enter a valid email address"),

  phoneNumber: z
    .string()
    .min(1, "Phone number is required")
    .regex(/^\+?[1-9]\d{1,14}$/, "Please enter a valid phone number")
    .transform((val) => val.replace(/\s+/g, "")), // Remove spaces

  testCustomerListVariables: z.string().optional().default("None"),

  variable1: z.string().optional().default(""),
});

export const sentenceSchema = z.object({
  id: z.string().optional(), // For React key
  content: z
    .string()
    .min(1, "Sentence is required")
    .max(1000, "Sentence is too long"),
  isAutoGenerated: z.boolean().default(false),
});
export const sentencesSchema = z.object({
  sentences: z
    .array(sentenceSchema)
    .min(1, "At least one sentence is required"),
  delay: z.string().optional(),
});
export const productSchema = z.object({
  productDescription: z.string().optional(),
});
export const callScriptSchema = z.object({
  callScript: z.string().optional(),
});
// export const agentSchema = basicSettingsSchema.merge(testCallSchema);
export const agentSchema = basicSettingsSchema
  .merge(testCallSchema)
  .merge(productSchema)
  .merge(sentencesSchema)
  .merge(callScriptSchema);

export type agentFormData = z.infer<typeof agentSchema>;

export type testCallFormData = z.infer<typeof testCallSchema>;
export type basicSettingsFormData = z.infer<typeof basicSettingsSchema>;
